# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NLq//r8vqexnriiV0TnQaSx+4hvHkkSPzwPETAGvBtpqOXXkPfoPazQl9MuTbE2dZnFtRzg92BCkITArXQ2PhzmJtVVjFn26W9v0uxlXfnUb5D8662V3jpLH/jOn6hiqlkoDs1wq8exRQryV8Qbhg6BUFKq4GbyjGboW8SOwk1cnzFAMz2gSZdNmb2H9pkL2HaZYHcvvzzAys7RjMfp1G8FHOo1bM0soqFm7kKrWAHX85oafGlk+n6W4cZUg5WDRHH7XG2Jyn3v4Zw01L8PiF4EAhXf8VvsbfQDvZQLnFMNZEvk5BY2m5VNLh+mtnnL8pvk5rjfaPCr4xoThQedu+NPJOIHaD8UScVH40QrwDs73lGHG71jragVFclJpbv1/kwqux1ju8woeYt6nvxg/Y0tVSN1fVLbHqREaIRck/topLQa6AXMvkeGIlTImwWXHSwNCpAWqB1DPTd+74jEIiroEAUo3jq3OaJLMVd6Zp+YJjSmHTqw8p5zyNWOuEl6dwDim0lPiWgUH1RaSSZgpiTo8yvvdyWwnSne4GVm00ZCbJLK9gShYAZEiaFEzE76BlEbBSr2D0dWzxOBzOtmI34V8xvApMeraFz8fLUG5oGJWnAID/nw2uTtFABvYcEgTHH6z47YqYIN7ojJlAKKEqE2gK87yTrBGGDbjEBTHpVQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
