travis:
  secure:
    BINSTAR_TOKEN: NLq//r8vqexnriiV0TnQaSx+4hvHkkSPzwPETAGvBtpqOXXkPfoPazQl9MuTbE2dZnFtRzg92BCkITArXQ2PhzmJtVVjFn26W9v0uxlXfnUb5D8662V3jpLH/jOn6hiqlkoDs1wq8exRQryV8Qbhg6BUFKq4GbyjGboW8SOwk1cnzFAMz2gSZdNmb2H9pkL2HaZYHcvvzzAys7RjMfp1G8FHOo1bM0soqFm7kKrWAHX85oafGlk+n6W4cZUg5WDRHH7XG2Jyn3v4Zw01L8PiF4EAhXf8VvsbfQDvZQLnFMNZEvk5BY2m5VNLh+mtnnL8pvk5rjfaPCr4xoThQedu+NPJOIHaD8UScVH40QrwDs73lGHG71jragVFclJpbv1/kwqux1ju8woeYt6nvxg/Y0tVSN1fVLbHqREaIRck/topLQa6AXMvkeGIlTImwWXHSwNCpAWqB1DPTd+74jEIiroEAUo3jq3OaJLMVd6Zp+YJjSmHTqw8p5zyNWOuEl6dwDim0lPiWgUH1RaSSZgpiTo8yvvdyWwnSne4GVm00ZCbJLK9gShYAZEiaFEzE76BlEbBSr2D0dWzxOBzOtmI34V8xvApMeraFz8fLUG5oGJWnAID/nw2uTtFABvYcEgTHH6z47YqYIN7ojJlAKKEqE2gK87yTrBGGDbjEBTHpVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
